#!/usr/bin/env sh

# Unload the macOS WindowManager process
launchctl unload -F /System/Library/LaunchAgents/com.apple.WindowManager.plist > /dev/null 2>&1 &

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
#yabai -m signal --add event=display_added action="sleep 1 && $HOME/.config/yabai/create_spaces.sh"
#yabai -m signal --add event=display_removed action="sleep 1 && $HOME/.config/yabai/create_spaces.sh"

#$HOME/.config/yabai/create_spaces.sh



# Global Settings
yabai -m config		mouse_follows_focus		off
yabai -m config		focus_follows_mouse		off

#yabai -m config		window_origin_display		default
yabai -m config		window_placement		second_child
yabai -m config		window_zoom_persist		off
yabai -m config		window_topmost			off
yabai -m config		window_shadow			float
yabai -m config		window_animation_duration	0.0
#yabai -m config		window_animation_frame_rate	120

yabai -m config		window_opacity_duration		0.0
yabai -m config		active_window_opacity		1.0
yabai -m config		normal_window_opacity		0.9
yabai -m config		window_opacity			off

yabai -m config		insert_feedback_color		0xff9dd274
yabai -m config		active_window_border_color	0xffe1e3e4
yabai -m config		normal_window_border_color	0xff494d64
yabai -m config		window_border_width		2
yabai -m config		window_border_radius		11
yabai -m config		window_border_blur		off
yabai -m config		window_border_hidpi		off
yabai -m config		window_border			on

yabai -m config		split_ratio			0.50
#yabai -m config		split_type			auto
yabai -m config		auto_balance			off

yabai -m config		top_padding			0
yabai -m config		bottom_padding			0
yabai -m config		left_padding			0
yabai -m config		right_padding			0
yabai -m config		window_gap			0

yabai -m config		mouse_modifier			fn
yabai -m config		mouse_action1			move
yabai -m config		mouse_action2			resize
yabai -m config		mouse_drop_action		swap

# Space Settings

# Exclude Apps
yabai -m rule --add	app="^(LuLu|Software Update|Dictionary|VLC|System Preferences|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice|Steam|Activity Monitor)$"	manage=off
yabai -m rule --add	app="^(System Settings|App Store|Calculator)$"	manage=off
yabai -m rule --add	app="^(微信|Clash for Windows|Raycast)$"	manage=off

yabai -m config		layout				bsp
# Finish
echo "yabai configuration loaded.."
